### ISSUE TITLE
[C++] Possible improvements on handling constructor/destructor

### ISSUE THREAD

**Issue by jasjuang** [20Tauri/DoxyDoxygen#107]
Please see below minimal code

```
class Sample
{
 public:
  
  Sample();
};
```

When I click the constructor and type alt+Q it shows 

```
class Sample
{
 public:
  /**
   * @brief      { function_description }
   */
  Sample();
};
```

Would it be possible for doxydoxygen to recognize that this is a constructor and generate default comment for empty constructors? For example, it is able to recognize the destructor and generate this by default

```
class Sample
{
 public:
  /**
   * @brief      Destroys the object.
   */
  ~Sample();
};
```

Another problem is when there is a DLL macro for the constructor and destructor, it thinks that the DLL macro is a return type, when in actuality constructor and destructor cannot have return types 

```
class Sample
{
 public:
  /**
   * @brief      { function_description }
   *
   * @return     { description_of_the_return_value }
   */
  WINDOWS_DLL Sample();
};
```
```
class Sample
{
 public:
  /**
   * @brief      Destroys the object.
   *
   * @return     { description_of_the_return_value }
   */
  WINDOWS_DLL ~Sample();
};
```

Would it be possible to fix this? Thanks!

**Comment by 20Tauri** [comment]
Thank for reporting

Destructor case is trivial to improve.
Constructors cases are slighty difficult to improve (especially when there are macros)
A way to solve this may be to let the plugin expanse some macros... The will also solve https://github.com/20Tauri/DoxyDoxygen/issues/105

**Comment by jasjuang** [comment]
@20Tauri Would it be possible to detect the name of the class and do a string match and see what are the constructors and destructors? I thought macros are easier to handle in constructors and destructors because in normal functions it might be hard to determine whether it's a macro or a return type but for constructors and destructors it will for sure be a macro.

**Comment by jasjuang** [comment]
I tested this out after the 0.65.0 update. The destructor is fixed, and it works even if I don't declare the macros in the doxydoxygen settings file.

However for the case of the constructor, regardless of having the DLL macros or not, it now shows `[doxy] cannot parse definition... command aborted`

**Comment by 20Tauri** [comment]
Works fine for me... Please let a blank line before destructor if you don't.
If still not work, start a comment and update it.

**Comment by jasjuang** [comment]
The destructor is working. It's the constructor that is not working. Please see screenshot. 

![screenshot from 2018-04-20 10-13-46](https://user-images.githubusercontent.com/11759200/39064501-9aa77cd0-4483-11e8-8376-411f2ccf25fc.png)

**Comment by 20Tauri** [comment]
You right, the problem is Sublime Text version dependent.Should be fixed in 0.65.1

**Comment by jasjuang** [comment]
I just tried 0.65.1 and it is fixed!
