### ISSUE TITLE
Problem in Python method with decorators

### ISSUE THREAD

**Issue by KuttKatrea** [20Tauri/DoxyDoxygen#81]
I'm working with this code

~~~python
@route('activation')
def activation(type, **kwargs):
    pass
~~~

But when typing <kbd>Alt</kbd>+<kbd>Q</kbd>

The cursor is moved to the annotation line, and the status bar displays:

> [doxy] cannot determine  command style => cannot wrap

If I add a space between the decorator and the definition it works as expected

~~~python
@route('activation')

def activation(type, **kwargs):
    pass
~~~

to

~~~python
@route('activation')

##
## @brief  { function_description }
##
## @param  type    The type
## @param  kwargs  The kwargs
##
## @return { description_of_the_return_value }
##
def activation(type, **kwargs):
    pass
~~~

**Comment by 20Tauri** [comment]
I'm tested your example with the lastest version of DoxyDoxygen and 2 versions of SublimeText.
I cannot reproduce.
Python annotation are supported for a long time new.... But you can try to force an update
The error "cannot determine command style" may refer a wrong "preferred_comments_styles" configuration. I've retested with the default one. Work !

If the problem persist after the two suggested check (and a sublime text restart). PLease go to "Preferences Setting -> Package Setting -> DoxyDoxygen" and "Send an anomaly report". It's the easier way to have your exact configuration to try to reproduce.

**Comment by KuttKatrea** [comment]
I'm testing with the default configuration for "preferred_comments_styles"
I tried to reinstall, and it still has the same behavior.

Also, I noted that when I remove the arguments in the annotation, it works as expected.

~~~python
import route


@route
def activation(type, **kwargs):
    pass
~~~

to

~~~python
##
## @brief  { function_description }
##
## @param  type    The type
## @param  kwargs  The kwargs
##
## @return { description_of_the_return_value }
##
@route
def activation(type, **kwargs):
    pass
~~~

I'm also sending you the "Anomaly report"

**Comment by 20Tauri** [comment]
I haven't received the "report" but I have reproduce it.
Problem occur with 0.58.0 and was fixed in 0.59.0 (released one month ago, but not available on all channels).
I just update the repo... Simply upgrade the plugin once package control detect the change (or switch to the "Evolution" version), problem will be fixed

**Comment by KuttKatrea** [comment]
I updated to the "Evolution" version (and disabled the normal one) but it's still not working :/

Haven't you received the report yet?

**Comment by 20Tauri** [comment]
I have not received yet and my analyze was wrong...
I've reproduced with 3124... And still reproduce with this version (you probably use 3124 or 3126)

The problem is `'activation'` is recognize as a DocString.
Waiting the final fix, you can use `##` + <kbd>enter</kbd> for the initial comment

**Comment by 20Tauri** [comment]
0.59.1 (evolution branch) has just been released and will fix this issue.

**Comment by KuttKatrea** [comment]
Version 0.59.1 tested and working. Thanks
